version: "3.7"

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    volumes:
      - boilerplate:/var/lib/postgresql/data
    networks:
      - boilerplate

volumes:
  boilerplate:

networks:
  boilerplate:
    driver: bridge